# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS = kernel
SUBDIRS += libc
SUBDIRS += fdlibm
SUBDIRS += rpc
SUBDIRS += startup
SUBDIRS += debug
SUBDIRS += eedebug
SUBDIRS += sbv
SUBDIRS += dma
SUBDIRS += graph
SUBDIRS += math3d
SUBDIRS += math
SUBDIRS += packet
SUBDIRS += draw
SUBDIRS += erl
SUBDIRS += erl-loader
SUBDIRS += mpeg
SUBDIRS += libgs
SUBDIRS += libvux
SUBDIRS += font
SUBDIRS += input
SUBDIRS += inputx
SUBDIRS += network

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
include $(PS2SDKSRC)/ee/Rules.release
